providers = ["python"]

[phases.setup]
nixPackages = ["python311Full"]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "bash start.sh"
